package com.e8.frame.model;

import java.util.Date;

public class Visits {

    private String id;

    private Date createTime;

    private String date;

    private Long ipCounts;

    private Long pvCounts;

    private String weekDay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visits.id
     *
     * @return the value of t_visits.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visits.id
     *
     * @param id the value for t_visits.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visits.create_time
     *
     * @return the value of t_visits.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visits.create_time
     *
     * @param createTime the value for t_visits.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visits.date
     *
     * @return the value of t_visits.date
     *
     * @mbggenerated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visits.date
     *
     * @param date the value for t_visits.date
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visits.ip_counts
     *
     * @return the value of t_visits.ip_counts
     *
     * @mbggenerated
     */
    public Long getIpCounts() {
        return ipCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visits.ip_counts
     *
     * @param ipCounts the value for t_visits.ip_counts
     *
     * @mbggenerated
     */
    public void setIpCounts(Long ipCounts) {
        this.ipCounts = ipCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visits.pv_counts
     *
     * @return the value of t_visits.pv_counts
     *
     * @mbggenerated
     */
    public Long getPvCounts() {
        return pvCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visits.pv_counts
     *
     * @param pvCounts the value for t_visits.pv_counts
     *
     * @mbggenerated
     */
    public void setPvCounts(Long pvCounts) {
        this.pvCounts = pvCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visits.week_day
     *
     * @return the value of t_visits.week_day
     *
     * @mbggenerated
     */
    public String getWeekDay() {
        return weekDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visits.week_day
     *
     * @param weekDay the value for t_visits.week_day
     *
     * @mbggenerated
     */
    public void setWeekDay(String weekDay) {
        this.weekDay = weekDay == null ? null : weekDay.trim();
    }
}